from guess_lang.py import *


def test_get_lang():
    assert get_lang('test/1') == 'clojure'
    # assert get_lang('test/2') == 'clojure'
    # assert get_lang('test/3') == 'clojure'
    # assert get_lang('test/4') == 'clojure'
    # assert get_lang('test/5') == 'python'
    # assert get_lang('test/6') == 'python'
    # assert get_lang('test/7') == 'python'
    # assert get_lang('test/8') == 'python'
    # assert get_lang('test/9') == 'javascript'
    # assert get_lang('test/10') == 'javascript'
    # assert get_lang('test/11') == 'javascript'
    # assert get_lang('test/12') == 'javascript'
    # assert get_lang('test/13') == 'ruby'
    # assert get_lang('test/14') == 'ruby'
    # assert get_lang('test/15') == 'ruby'
    # assert get_lang('test/16') == 'haskell'
    # assert get_lang('test/17') == 'haskell'
    # assert get_lang('test/18') == 'haskell'
    # assert get_lang('test/19') == 'scheme'
    # assert get_lang('test/20') == 'scheme'
    # assert get_lang('test/21') == 'scheme'
    # assert get_lang('test/22') == 'java'
    # assert get_lang('test/23') == 'java'
    # assert get_lang('test/24') == 'scala'
    # assert get_lang('test/25') == 'scala'
    # assert get_lang('test/26') == 'tcl'
    # assert get_lang('test/27') == 'tcl'
    # assert get_lang('test/28') == 'php'
    # assert get_lang('test/29') == 'php'
    # assert get_lang('test/30') == 'php'
    # assert get_lang('test/31') == 'ocaml'
    # assert get_lang('test/32') == 'ocaml'
